name: test

on:
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    strategy:
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
